window.LANGS = window.LANGS || {};
window.LANGS.cs = {
  /* Stats */
  lbl_connected:        'P\u0159ipojeno',
  lbl_clients_active:   'Aktivn\u00ED klienti',
  lbl_server_bridges:   'Serverov\u00E9 mosty',
  lbl_updated:          'Aktualizov\u00E1no',
  lbl_mode:             'Re\u017Eim',
  /* Card errors */
  err_host_api:         '\u26A0 API hostitele nedostupn\u00E9',
  err_printer_api:      '\u26A0 API tisk\u00E1rny nedostupn\u00E9',
  /* Section titles */
  sec_uart_bridges:     'UART mosty',
  sec_services:         'Slu\u017Eby',
  sec_tcp_forwards:     'TCP p\u0159esm\u011Brov\u00E1n\u00ED',
  /* Group buttons */
  btn_start_all:        '\u25B6 Spustit v\u0161e',
  btn_stop_all:         '\u25A0 Zastavit v\u0161e',
  btn_restart_all:      '\u21BA Restartovat v\u0161e',
  /* Table headers */
  th_port:              'Port',
  th_pty:               'PTY',
  th_status:            'Stav',
  th_status_short:      'St',
  th_pid:               'PID',
  th_since:             'Od',
  th_conn:              'Spoj.',
  th_control:           'Ovl\u00E1d\u00E1n\u00ED',
  th_log:               'Log',
  th_service:           'Slu\u017Eba',
  th_name:              'N\u00E1zev',
  th_forward:           'P\u0159esm.',
  th_src_dst:           'Src\u2192Dst',
  th_systemd_unit:      'Systemd jednotka',
  th_tcp_port:          'TCP port',
  th_enabled:           'Povoleno',
  th_src_port:          'Src port',
  th_dst_port:          'Dst port',
  th_en:                'Povol.',
  th_local:             '\uD83D\uDD12 Lok\u00E1ln\u00ED',
  tip_keep_local:       'Ponechat aktivn\u00ED v lok\u00E1ln\u00EDm re\u017Eimu',
  /* Links */
  lnk_action_log:       'log akc\u00ED',
  /* General */
  loading:              'Na\u010D\u00EDt\u00E1n\u00ED\u2026',
  no_data:              '\u017D\u00E1dn\u00E1 data',
  saving:               'ukl\u00E1d\u00E1n\u00ED\u2026',
  saved:                '\u2713 ulo\u017Eeno',
  load_error:           'chyba na\u010Dten\u00ED',
  close_esc:            'Zav\u0159\u00EDt (Esc)',
  save_enter:           'Ulo\u017Eit (Enter)',
  /* Service states */
  st_running:           'b\u011B\u017E\u00ED',
  st_stopped:           'zastaveno',
  st_starting:          'spou\u0161t\u011Bn\u00ED',
  st_stopping:          'zastavov\u00E1n\u00ED',
  st_failed:            'selh\u00E1n\u00ED',
  st_unknown:           'nezn\u00E1m\u00E9',
  st_disabled:          'zak\u00E1z\u00E1no',
  /* Mode */
  mode_local:           'Lok\u00E1ln\u00ED',
  mode_remote:          'Vzd\u00E1len\u00FD',
  mode_to_local:        '\u2192 Lok\u00E1ln\u00ED',
  mode_to_remote:       '\u2192 Vzd\u00E1len\u00FD',
  /* Log modal */
  log_title:            'Log',
  log_no_log:           '(pr\u00E1zdn\u00FD log)',
  log_client_action:    'Log akc\u00ED klienta',
  log_server_action:    'Log akc\u00ED serveru',
  log_client_bridge:    'Den\u00EDk: klipper-bridge-client@{port}',
  log_client_svc:       'Log slu\u017Eby klienta: {name}',
  log_server_svc:       'Log slu\u017Eby serveru: {name}',
  log_server_bridge:    'Log mostu serveru: port {port}',
  log_server_tcpfwd:    'Log TCP p\u0159esm.: port {port}',
  /* Ports modal */
  modal_port_settings:  'Nastaven\u00ED port\u016F',
  modal_port_hint:      'sd\u00EDlen\u00E9 \u2014 aplikuje se na klienta i server p\u0159i ulo\u017Een\u00ED',
  btn_add:              '+ P\u0159idat',
  btn_save_apply_both:  '\u2713 Ulo\u017Eit & pou\u017E\u00EDt na oba',
  ph_port:              'port',
  /* Client services */
  modal_client_svcs:      'Klientsk\u00E9 slu\u017Eby',
  modal_client_svcs_hint: 'systemd jednotky na hostiteli',
  btn_save:             '\u2713 Ulo\u017Eit',
  ph_name:              'n\u00E1zev',
  ph_unit:              'jednotka.service',
  /* Server services */
  modal_server_svcs:      'Slu\u017Eby tisk\u00E1rny',
  modal_server_svcs_hint: 'S-skripty na tisk\u00E1rn\u011B',
  ssvc_lbl_name:        'N\u00E1zev',
  ssvc_lbl_script:      'Skript',
  ssvc_lbl_pre_start:   'P\u0159ed startem',
  ssvc_lbl_mode_switch: 'P\u0159ep\u00EDn\u00E1n\u00ED re\u017Eimu',
  ssvc_opt_no_action:   '\u2014 \u017E\u00E1dn\u00E1 akce',
  ssvc_opt_start_on_local: '\u25B6 Spustit p\u0159i Lok\u00E1ln\u00EDm / Stop p\u0159i Vzd\u00E1len\u00E9m',
  ssvc_opt_stop_on_local:  '\u23F9 Stop p\u0159i Lok\u00E1ln\u00EDm / Spustit p\u0159i Vzd\u00E1len\u00E9m',
  ssvc_lbl_log_path:    'Cesta k logu',
  ssvc_ph_log_optional: 'voliteln\u011B',
  ssvc_lbl_start_verb:  'P\u0159\u00EDkaz startu',
  ssvc_lbl_stop_verb:   'P\u0159\u00EDkaz stopu',
  ssvc_lbl_chroot:      'Chroot',
  ssvc_lbl_stop_on_start:  '\u23F9 Zastavit p\u0159i startu API',
  ssvc_lbl_start_on_start: '\u25B6 Spustit p\u0159i startu API',
  ssvc_ph_script:       '/opt/config/mod/.shell/root/Sxx',
  ssvc_ph_pre_start:    'p\u0159\u00EDkaz p\u0159ed startem (voliteln\u011B)',
  /* TCP Forwards */
  modal_tcp_fwds:       'TCP P\u0159esm\u011Brov\u00E1n\u00ED',
  btn_save_apply:       '\u2713 Ulo\u017Eit & pou\u017E\u00EDt',
  /* Config bar */
  btn_cfg_ports:        'Porty',
  btn_cfg_tcp_fwds:     'TCP p\u0159esm.',
  btn_cfg_host_svcs:    'Slu\u017Eby hostitele',
  btn_cfg_printer_svcs: 'Slu\u017Eby tisk\u00E1rny',
  /* Footer */
  footer_created:       'Vytvo\u0159eno s \u2764\uFE0F od',
  footer_special:       'speci\u00E1ln\u011B pro',
  footer_web:           'web',
  footer_host:          'host',
  footer_printer:       'tisk\u00E1rna',
  /* Toasts */
  toast_invalid_port:   'Neplatn\u00FD port',
  toast_port_exists:    'Port je ji\u017E v seznamu',
  toast_saving_ports:   '\u2699 Ukl\u00E1d\u00E1n\u00ED port\u016F\u2026',
  toast_saved_both:     '\u2713 Ulo\u017Eeno & pou\u017Eito na oba',
  toast_name_unit_req:  'N\u00E1zev a jednotka jsou povinn\u00E9',
  toast_fill_fields:    'Vypl\u0148te n\u00E1zev, src a dst',
  toast_client_svcs_saved: '\u2713 Klientsk\u00E9 slu\u017Eby ulo\u017Eeny',
  toast_server_svcs_saved: '\u2713 Slu\u017Eby tisk\u00E1rny ulo\u017Eeny',
  toast_tcp_fwds_saved: 'TCP p\u0159esm\u011Brov\u00E1n\u00ED ulo\u017Eena & aplikuj\u00ED se',
  toast_action_done:    'hotovo',
  toast_error:          'Chyba: {msg}',
  toast_done:           '\u2713 {label}: hotovo',
};
