window.LANGS = window.LANGS || {};
window.LANGS.en = {
  /* Stats */
  lbl_connected:        'Connected',
  lbl_clients_active:   'Clients active',
  lbl_server_bridges:   'Server bridges',
  lbl_updated:          'Updated',
  lbl_mode:             'Mode',
  /* Card errors */
  err_host_api:         '\u26A0 Host API unavailable',
  err_printer_api:      '\u26A0 Printer API unavailable',
  /* Section titles */
  sec_uart_bridges:     'UART Bridges',
  sec_services:         'Services',
  sec_tcp_forwards:     'TCP Forwards',
  /* Group buttons */
  btn_start_all:        '\u25B6 Start all',
  btn_stop_all:         '\u25A0 Stop all',
  btn_restart_all:      '\u21BA Restart all',
  /* Table headers */
  th_port:              'Port',
  th_pty:               'PTY',
  th_status:            'Status',
  th_status_short:      'St',
  th_pid:               'PID',
  th_since:             'Since',
  th_conn:              'Conn',
  th_control:           'Control',
  th_log:               'Log',
  th_service:           'Service',
  th_name:              'Name',
  th_forward:           'Forward',
  th_src_dst:           'Src\u2192Dst',
  th_systemd_unit:      'Systemd Unit',
  th_tcp_port:          'TCP Port',
  th_enabled:           'Enabled',
  th_src_port:          'Src port',
  th_dst_port:          'Dst port',
  th_en:                'En',
  th_local:             '\uD83D\uDD12 Local',
  tip_keep_local:       'Keep running in Local mode',
  /* Links */
  lnk_action_log:       'action log',
  /* General */
  loading:              'Loading\u2026',
  no_data:              'No data',
  saving:               'saving\u2026',
  saved:                '\u2713 saved',
  load_error:           'load error',
  close_esc:            'Close (Esc)',
  save_enter:           'Save (Enter)',
  /* Service states */
  st_running:           'running',
  st_stopped:           'stopped',
  st_starting:          'starting',
  st_stopping:          'stopping',
  st_failed:            'failed',
  st_unknown:           'unknown',
  st_disabled:          'disabled',
  /* Mode */
  mode_local:           'Local',
  mode_remote:          'Remote',
  mode_to_local:        '\u2192 Local',
  mode_to_remote:       '\u2192 Remote',
  /* Log modal */
  log_title:            'Log',
  log_no_log:           '(no log)',
  log_client_action:    'Client action log',
  log_server_action:    'Server action log',
  log_client_bridge:    'Journal: klipper-bridge-client@{port}',
  log_client_svc:       'Client service log: {name}',
  log_server_svc:       'Server service log: {name}',
  log_server_bridge:    'Server bridge log: port {port}',
  log_server_tcpfwd:    'TCP fwd log: port {port}',
  /* Ports modal */
  modal_port_settings:  'Port Settings',
  modal_port_hint:      'shared \u2014 applies to client & server on save',
  btn_add:              '+ Add',
  btn_save_apply_both:  '\u2713 Save & apply both',
  ph_port:              'port',
  /* Client services */
  modal_client_svcs:      'Client Services',
  modal_client_svcs_hint: 'systemd units monitored on the host',
  btn_save:             '\u2713 Save',
  ph_name:              'name',
  ph_unit:              'unit.service',
  /* Server services */
  modal_server_svcs:      'Server Services',
  modal_server_svcs_hint: 'S-scripts on the printer',
  ssvc_lbl_name:        'Name',
  ssvc_lbl_script:      'Script',
  ssvc_lbl_pre_start:   'Pre-start',
  ssvc_lbl_mode_switch: 'Mode switch',
  ssvc_opt_no_action:   '\u2014 no action',
  ssvc_opt_start_on_local: '\u25B6 Start on Local / Stop on Remote',
  ssvc_opt_stop_on_local:  '\u23F9 Stop on Local / Start on Remote',
  ssvc_lbl_log_path:    'Log path',
  ssvc_ph_log_optional: 'optional',
  ssvc_lbl_start_verb:  'Start verb',
  ssvc_lbl_stop_verb:   'Stop verb',
  ssvc_lbl_chroot:      'Chroot',
  ssvc_lbl_stop_on_start:  '\u23F9 Stop on API start',
  ssvc_lbl_start_on_start: '\u25B6 Start on API start',
  ssvc_ph_script:       '/opt/config/mod/.shell/root/Sxx',
  ssvc_ph_pre_start:    'optional cmd before start',
  /* TCP Forwards */
  modal_tcp_fwds:       'TCP Port Forwards',
  btn_save_apply:       '\u2713 Save & apply',
  /* Config bar */
  btn_cfg_ports:        'Ports',
  btn_cfg_tcp_fwds:     'TCP Forwards',
  btn_cfg_host_svcs:    'Host services',
  btn_cfg_printer_svcs: 'Printer services',
  /* Footer */
  footer_created:       'Created with \u2764\uFE0F by',
  footer_special:       'special for',
  footer_web:           'web',
  footer_host:          'host',
  footer_printer:       'printer',
  /* Toasts */
  toast_invalid_port:   'Invalid port',
  toast_port_exists:    'Port already in list',
  toast_saving_ports:   '\u2699 Saving ports\u2026',
  toast_saved_both:     '\u2713 Saved & applied to both',
  toast_name_unit_req:  'Name and unit required',
  toast_fill_fields:    'Fill name, src and dst',
  toast_client_svcs_saved: '\u2713 Client services saved',
  toast_server_svcs_saved: '\u2713 Server services saved',
  toast_tcp_fwds_saved: 'TCP forwards saved & applying',
  toast_action_done:    'done',
  toast_error:          'Error: {msg}',
  toast_done:           '\u2713 {label}: done',
};
