window.LANGS = window.LANGS || {};
window.LANGS.pt = {
  /* Stats */
  lbl_connected:        'Conectado',
  lbl_clients_active:   'Clientes activos',
  lbl_server_bridges:   'Bridges do servidor',
  lbl_updated:          'Actualizado',
  lbl_mode:             'Modo',
  /* Card errors */
  err_host_api:         '\u26A0 API do host indispon\u00EDvel',
  err_printer_api:      '\u26A0 API da impressora indispon\u00EDvel',
  /* Section titles */
  sec_uart_bridges:     'Bridges UART',
  sec_services:         'Servi\u00E7os',
  sec_tcp_forwards:     'Reencaminhamentos TCP',
  /* Group buttons */
  btn_start_all:        '\u25B6 Iniciar todos',
  btn_stop_all:         '\u25A0 Parar todos',
  btn_restart_all:      '\u21BA Reiniciar todos',
  /* Table headers */
  th_port:              'Porto',
  th_pty:               'PTY',
  th_status:            'Estado',
  th_status_short:      'Est',
  th_pid:               'PID',
  th_since:             'Desde',
  th_conn:              'Lig.',
  th_control:           'Controlo',
  th_log:               'Log',
  th_service:           'Servi\u00E7o',
  th_name:              'Nome',
  th_forward:           'Reencam.',
  th_src_dst:           'Src\u2192Dst',
  th_systemd_unit:      'Unidade Systemd',
  th_tcp_port:          'Porto TCP',
  th_enabled:           'Activo',
  th_src_port:          'Porto src',
  th_dst_port:          'Porto dst',
  th_en:                'Act.',
  th_local:             '\uD83D\uDD12 Local',
  tip_keep_local:       'Manter activo no modo Local',
  /* Links */
  lnk_action_log:       'log de ac\u00E7\u00F5es',
  /* General */
  loading:              'A carregar\u2026',
  no_data:              'Sem dados',
  saving:               'a guardar\u2026',
  saved:                '\u2713 guardado',
  load_error:           'erro de carregamento',
  close_esc:            'Fechar (Esc)',
  save_enter:           'Guardar (Enter)',
  /* Service states */
  st_running:           'a funcionar',
  st_stopped:           'parado',
  st_starting:          'a iniciar',
  st_stopping:          'a parar',
  st_failed:            'falha',
  st_unknown:           'desconhecido',
  st_disabled:          'desactivado',
  /* Mode */
  mode_local:           'Local',
  mode_remote:          'Remoto',
  mode_to_local:        '\u2192 Local',
  mode_to_remote:       '\u2192 Remoto',
  /* Log modal */
  log_title:            'Log',
  log_no_log:           '(sem log)',
  log_client_action:    'Log de ac\u00E7\u00F5es do cliente',
  log_server_action:    'Log de ac\u00E7\u00F5es do servidor',
  log_client_bridge:    'Di\u00E1rio: klipper-bridge-client@{port}',
  log_client_svc:       'Log de servi\u00E7o do cliente: {name}',
  log_server_svc:       'Log de servi\u00E7o do servidor: {name}',
  log_server_bridge:    'Log de bridge do servidor: porto {port}',
  log_server_tcpfwd:    'Log TCP reencam.: porto {port}',
  /* Ports modal */
  modal_port_settings:  'Defini\u00E7\u00F5es de portos',
  modal_port_hint:      'partilhado \u2014 aplicado ao cliente e servidor ao guardar',
  btn_add:              '+ Adicionar',
  btn_save_apply_both:  '\u2713 Guardar & aplicar a ambos',
  ph_port:              'porto',
  /* Client services */
  modal_client_svcs:      'Servi\u00E7os do cliente',
  modal_client_svcs_hint: 'unidades systemd monitoradas no host',
  btn_save:             '\u2713 Guardar',
  ph_name:              'nome',
  ph_unit:              'unidade.service',
  /* Server services */
  modal_server_svcs:      'Servi\u00E7os da impressora',
  modal_server_svcs_hint: 'S-scripts na impressora',
  ssvc_lbl_name:        'Nome',
  ssvc_lbl_script:      'Script',
  ssvc_lbl_pre_start:   'Pr\u00E9-in\u00EDcio',
  ssvc_lbl_mode_switch: 'Comuta\u00E7\u00E3o de modo',
  ssvc_opt_no_action:   '\u2014 sem ac\u00E7\u00E3o',
  ssvc_opt_start_on_local: '\u25B6 Iniciar em Local / Parar em Remoto',
  ssvc_opt_stop_on_local:  '\u23F9 Parar em Local / Iniciar em Remoto',
  ssvc_lbl_log_path:    'Caminho do log',
  ssvc_ph_log_optional: 'opcional',
  ssvc_lbl_start_verb:  'Verbo de in\u00EDcio',
  ssvc_lbl_stop_verb:   'Verbo de paragem',
  ssvc_lbl_chroot:      'Chroot',
  ssvc_lbl_stop_on_start:  '\u23F9 Parar ao iniciar API',
  ssvc_lbl_start_on_start: '\u25B6 Iniciar ao iniciar API',
  ssvc_ph_script:       '/opt/config/mod/.shell/root/Sxx',
  ssvc_ph_pre_start:    'comando antes de iniciar (opcional)',
  /* TCP Forwards */
  modal_tcp_fwds:       'Reencaminhamentos TCP',
  btn_save_apply:       '\u2713 Guardar & aplicar',
  /* Config bar */
  btn_cfg_ports:        'Portos',
  btn_cfg_tcp_fwds:     'TCP Reencam.',
  btn_cfg_host_svcs:    'Servi\u00E7os do host',
  btn_cfg_printer_svcs: 'Servi\u00E7os da impressora',
  /* Footer */
  footer_created:       'Criado com \u2764\uFE0F por',
  footer_special:       'especialmente para',
  footer_web:           'web',
  footer_host:          'host',
  footer_printer:       'impressora',
  /* Toasts */
  toast_invalid_port:   'Porto inv\u00E1lido',
  toast_port_exists:    'Porto j\u00E1 na lista',
  toast_saving_ports:   '\u2699 A guardar portos\u2026',
  toast_saved_both:     '\u2713 Guardado & aplicado a ambos',
  toast_name_unit_req:  'Nome e unidade necess\u00E1rios',
  toast_fill_fields:    'Preencha nome, src e dst',
  toast_client_svcs_saved: '\u2713 Servi\u00E7os do cliente guardados',
  toast_server_svcs_saved: '\u2713 Servi\u00E7os da impressora guardados',
  toast_tcp_fwds_saved: 'TCP reencaminhamentos guardados & a aplicar',
  toast_action_done:    'conclu\u00EDdo',
  toast_error:          'Erro: {msg}',
  toast_done:           '\u2713 {label}: conclu\u00EDdo',
};
